package com.waynetye.myapp.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "categories")
public class Category {

    @Id
    private String id;         // Unique ID generated by MongoDB
    private String name;       // Name of the category (e.g., Food, Travel)
    private String userId;     // Optional: categories can be user-specific

    // Default constructor
    public Category() {}

    // Constructor with fields
    public Category(String name, String userId) {
        this.name = name;
        this.userId = userId;
    }

    // Getters and Setters
    public String getId() { return id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
}
