package com.waynetye.myapp.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "expenses")
public class Expense {

    @Id
    private String id;          // Unique ID generated by MongoDB
    private String monthId;     // Reference to the Month this expense belongs to
    private String categoryId;  // Reference to the Category
    private double amount;      // Expense amount
    private String description; // Optional description of the expense

    // Default constructor
    public Expense() {}

    // Constructor with fields
    public Expense(String monthId, String categoryId, double amount, String description) {
        this.monthId = monthId;
        this.categoryId = categoryId;
        this.amount = amount;
        this.description = description;
    }

    // Getters and Setters
    public String getId() { return id; }

    public String getMonthId() { return monthId; }
    public void setMonthId(String monthId) { this.monthId = monthId; }

    public String getCategoryId() { return categoryId; }
    public void setCategoryId(String categoryId) { this.categoryId = categoryId; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
}
