package com.waynetye.myapp.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

@Document(collection = "months")
public class Month {

    @Id
    private String id;             // Unique ID generated by MongoDB
    private String name;           // Month name, e.g., "October 2025"
    private String userId;         // Reference to the User who owns this month
    private List<String> expenseIds; // List of Expense IDs for this month

    // Default constructor
    public Month() {}

    // Constructor with fields
    public Month(String name, String userId) {
        this.name = name;
        this.userId = userId;
    }

    // Getters and Setters
    public String getId() { return id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public List<String> getExpenseIds() { return expenseIds; }
    public void setExpenseIds(List<String> expenseIds) { this.expenseIds = expenseIds; }
}
